numeric_vector <- c(10, 20, 30, 40, 50)
character_vector <- c("Apple", "Banana", "Cherry", "Date", "Elderberry")
logical_vector <- c(TRUE, FALSE, TRUE, TRUE, FALSE)
print("Numeric Vector:")
print(numeric_vector)
print("Character Vector:")
print(character_vector)
print("Logical Vector:")
print(logical_vector)
print("Type of Numeric Vector:")
print(typeof(numeric_vector))
print("Type of Character Vector:")
print(typeof(character_vector))
print("Type of Logical Vector:")
print(typeof(logical_vector))
